In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

#### Load the dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

### Scaling Numeric Columns

In [7]:
scaler = StandardScaler().fit(X_train.select_dtypes(include='number'))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 1.76516219,  0.33230299,  1.71996026, ...,  0.70089493,
         0.50333065, -1.09488579],
       [ 0.4473609 ,  0.23482486,  0.42351583, ...,  0.4994311 ,
         1.72637919,  1.19825899],
       [-0.17803633, -0.0808186 , -0.16210548, ...,  0.4603411 ,
        -0.37321385, -0.39411282],
       ...,
       [-0.75038647, -0.25024487, -0.74813068, ..., -0.89593149,
        -1.09786615, -0.41998752],
       [ 1.78749781,  0.37640023,  1.84516206, ...,  1.50524682,
         0.27707458, -0.45718239],
       [ 0.2267967 , -0.03207954,  0.19855647, ...,  0.51446571,
         0.0951204 ,  0.0295853 ]])

### Encoding the Categorical Columns

In [9]:
encoder = LabelEncoder().fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

## Changing the numpy arrays to pytorch

In [11]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [12]:
X_train_tensor.dtype, type(X_train_tensor), X_train_tensor.shape

(torch.float64, torch.Tensor, torch.Size([455, 30]))

In [13]:
X_train_tensor

tensor([[ 1.7652,  0.3323,  1.7200,  ...,  0.7009,  0.5033, -1.0949],
        [ 0.4474,  0.2348,  0.4235,  ...,  0.4994,  1.7264,  1.1983],
        [-0.1780, -0.0808, -0.1621,  ...,  0.4603, -0.3732, -0.3941],
        ...,
        [-0.7504, -0.2502, -0.7481,  ..., -0.8959, -1.0979, -0.4200],
        [ 1.7875,  0.3764,  1.8452,  ...,  1.5052,  0.2771, -0.4572],
        [ 0.2268, -0.0321,  0.1986,  ...,  0.5145,  0.0951,  0.0296]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model for the Nerual Network(start)

In [15]:
class MySimpleNN():
    
    def __init__(self, train_data):
        self.weights = torch.rand(train_data.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    
    def forward(self, train_data):
        z = torch.matmul(train_data, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_true):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss

#### Important Parameters to use

In [39]:
learning_rate = 0.08
epochs = 160

### Training Pipeline

In [40]:
# create the model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
        
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss for each epoch
    print(f'Epoch: {epoch+1} | Loss = {loss.item()}')

Epoch: 1 | Loss = 3.4036011778550903
Epoch: 2 | Loss = 3.2986115107591556
Epoch: 3 | Loss = 3.1897129961935864
Epoch: 4 | Loss = 3.076246040113669
Epoch: 5 | Loss = 2.9590681924665465
Epoch: 6 | Loss = 2.8385577133578446
Epoch: 7 | Loss = 2.7099682809465455
Epoch: 8 | Loss = 2.5808324894515033
Epoch: 9 | Loss = 2.4516785042168387
Epoch: 10 | Loss = 2.3148141595175233
Epoch: 11 | Loss = 2.178606812265684
Epoch: 12 | Loss = 2.04549296674623
Epoch: 13 | Loss = 1.9137850051673464
Epoch: 14 | Loss = 1.781837721566072
Epoch: 15 | Loss = 1.6553230523313003
Epoch: 16 | Loss = 1.5352310437563546
Epoch: 17 | Loss = 1.4194698193591246
Epoch: 18 | Loss = 1.305896622002003
Epoch: 19 | Loss = 1.202935786826826
Epoch: 20 | Loss = 1.111673808298682
Epoch: 21 | Loss = 1.0328776232771988
Epoch: 22 | Loss = 0.9668329792370441
Epoch: 23 | Loss = 0.9132210530258497
Epoch: 24 | Loss = 0.8710808982072261
Epoch: 25 | Loss = 0.8388980652567568
Epoch: 26 | Loss = 0.8148251607970481
Epoch: 27 | Loss = 0.7969710042508582
Epoch: 28 | Loss = 0.78364879906624
Epoch: 29 | Loss = 0.7735082950270916
Epoch: 30 | Loss = 0.7655529976985341
Epoch: 31 | Loss = 0.7590887513819979
Epoch: 32 | Loss = 0.7536501512889148
Epoch: 33 | Loss = 0.7489320989555128
Epoch: 34 | Loss = 0.7447365110990307
Epoch: 35 | Loss = 0.7409346340778701
Epoch: 36 | Loss = 0.7374418647124366
Epoch: 37 | Loss = 0.7342014954466304
Epoch: 38 | Loss = 0.7311744351775098
Epoch: 39 | Loss = 0.7283327847521885
Epoch: 40 | Loss = 0.7256558435656432
Epoch: 41 | Loss = 0.7231276286841763
Epoch: 42 | Loss = 0.720735327593436
Epoch: 43 | Loss = 0.7184683250181904
Epoch: 44 | Loss = 0.7163175825236916
Epoch: 45 | Loss = 0.7142752354602083
Epoch: 46 | Loss = 0.7123343246066295
Epoch: 47 | Loss = 0.7104886121274206
Epoch: 48 | Loss = 0.7087324510840894
Epoch: 49 | Loss = 0.7070606896520677
Epoch: 50 | Loss = 0.7054685984116402
Epoch: 51 | Loss = 0.7039518134565829
Epoch: 52 | Loss = 0.7025062907213642
Epoch: 53 | Loss = 0.7011282685486354
Epoch: 54 | Loss = 0.699814236514925
Epoch: 55 | Loss = 0.6985609091518769
Epoch: 56 | Loss = 0.697365203592103
Epoch: 57 | Loss = 0.6962242204221903
Epoch: 58 | Loss = 0.6951352271942423
Epoch: 59 | Loss = 0.6940956441637488
Epoch: 60 | Loss = 0.6931030319048729
Epoch: 61 | Loss = 0.6921550805161439
Epoch: 62 | Loss = 0.6912496001771399
Epoch: 63 | Loss = 0.6903845128544718
Epoch: 64 | Loss = 0.6895578449859808
Epoch: 65 | Loss = 0.688767720997395
Epoch: 66 | Loss = 0.6880123575269135
Epoch: 67 | Loss = 0.6872900582512089
Epoch: 68 | Loss = 0.6865992092217288
Epoch: 69 | Loss = 0.6859382746334315
Epoch: 70 | Loss = 0.6853057929595621
Epoch: 71 | Loss = 0.6847003733960177
Epoch: 72 | Loss = 0.6841206925675395
Epoch: 73 | Loss = 0.683565491455513
Epoch: 74 | Loss = 0.6830335725137748
Epoch: 75 | Loss = 0.6825237969445487
Epoch: 76 | Loss = 0.6820350821116414
Epoch: 77 | Loss = 0.6815663990723276
Epoch: 78 | Loss = 0.6811167702130524
Epoch: 79 | Loss = 0.6806852669772319
Epoch: 80 | Loss = 0.6802710076760743
Epoch: 81 | Loss = 0.6798731553755439
Epoch: 82 | Loss = 0.6794909158543851
Epoch: 83 | Loss = 0.6791235356295645
Epoch: 84 | Loss = 0.6787703000466151
Epoch: 85 | Loss = 0.6784305314332204
Epoch: 86 | Loss = 0.6781035873149946
Epoch: 87 | Loss = 0.677788858692849
Epoch: 88 | Loss = 0.6774857683815888
Epoch: 89 | Loss = 0.6771937694095315
Epoch: 90 | Loss = 0.676912343478955
Epoch: 91 | Loss = 0.6766409994871554
Epoch: 92 | Loss = 0.676379272107774
Epoch: 93 | Loss = 0.676126720431933
Epoch: 94 | Loss = 0.6758829266685374
Epoch: 95 | Loss = 0.6756474949029427
Epoch: 96 | Loss = 0.6754200499130008
Epoch: 97 | Loss = 0.6752002360413418
Epoch: 98 | Loss = 0.6749877161225792
Epoch: 99 | Loss = 0.6747821704639987
Epoch: 100 | Loss = 0.6745832958781601
Epoch: 101 | Loss = 0.674390804765746
Epoch: 102 | Loss = 0.6742044242469039
Epoch: 103 | Loss = 0.6740238953392722
Epoch: 104 | Loss = 0.6738489721808276
Epoch: 105 | Loss = 0.6736794212956773
Epoch: 106 | Loss = 0.6735150209008977
Epoch: 107 | Loss = 0.6733555602525346
Epoch: 108 | Loss = 0.6732008390288924
Epoch: 109 | Loss = 0.6730506667492689
Epoch: 110 | Loss = 0.6729048622263303
Epoch: 111 | Loss = 0.6727632530503668
Epoch: 112 | Loss = 0.6726256751037202
Epoch: 113 | Loss = 0.6724919721037316
Epoch: 114 | Loss = 0.6723619951726163
Epoch: 115 | Loss = 0.6722356024327445
Epoch: 116 | Loss = 0.6721126586258537
Epoch: 117 | Loss = 0.6719930347548101
Epoch: 118 | Loss = 0.6718766077465747
Epoch: 119 | Loss = 0.671763260135118
Epoch: 120 | Loss = 0.671652879763082
Epoch: 121 | Loss = 0.6715453595010497
Epoch: 122 | Loss = 0.6714405969833499
Epoch: 123 | Loss = 0.6713384943593865
Epoch: 124 | Loss = 0.6712389580595284
Epoch: 125 | Loss = 0.6711418985746664
Epoch: 126 | Loss = 0.6710472302485864
Epoch: 127 | Loss = 0.6709548710823645
Epoch: 128 | Loss = 0.6708647425500345
Epoch: 129 | Loss = 0.6707767694248287
Epoch: 130 | Loss = 0.6706908796153318
Epoch: 131 | Loss = 0.6706070040109335
Epoch: 132 | Loss = 0.6705250763360012
Epoch: 133 | Loss = 0.6704450330122328
Epoch: 134 | Loss = 0.6703668130286841
Epoch: 135 | Loss = 0.6702903578189957
Epoch: 136 | Loss = 0.6702156111453784
Epoch: 137 | Loss = 0.6701425189889425
Epoch: 138 | Loss = 0.6700710294459833
Epoch: 139 | Loss = 0.6700010926298616
Epoch: 140 | Loss = 0.6699326605781386
Epoch: 141 | Loss = 0.6698656871646517
Epoch: 142 | Loss = 0.6698001280162328
Epoch: 143 | Loss = 0.6697359404337941
Epoch: 144 | Loss = 0.6696730833175205
Epoch: 145 | Loss = 0.6696115170959278
Epoch: 146 | Loss = 0.6695512036585619
Epoch: 147 | Loss = 0.6694921062921233
Epoch: 148 | Loss = 0.6694341896198225
Epoch: 149 | Loss = 0.6693774195437767
Epoch: 150 | Loss = 0.669321763190279
Epoch: 151 | Loss = 0.6692671888577724
Epoch: 152 | Loss = 0.6692136659673793
Epoch: 153 | Loss = 0.6691611650158416
Epoch: 154 | Loss = 0.6691096575307398
Epoch: 155 | Loss = 0.6690591160278629
Epoch: 156 | Loss = 0.6690095139706118
Epoch: 157 | Loss = 0.6689608257313278
Epoch: 158 | Loss = 0.668913026554439
Epoch: 159 | Loss = 0.6688660925213296
Epoch: 160 | Loss = 0.6688200005168381

In [41]:
model.weights[:10], model.bias

(tensor([[-0.1717],
         [-0.0817],
         [-0.3974],
         [ 0.3846],
         [ 0.2421],
         [-0.2389],
         [-0.2206],
         [ 0.3066],
         [-0.1474],
         [ 0.1542]], dtype=torch.float64, grad_fn=<SliceBackward0>),
 tensor([-0.4812], dtype=torch.float64, requires_grad=True))

In [44]:
y_pred[:10]

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

### Evaluation

In [42]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.7).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6378886103630066