In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [5]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

In [ ]:
scaler = StandardScaler().fit(X_train.select_dtypes(include='number'))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.53008694,  0.05609295,  0.47820047, ...,  0.54252214,
        -0.43591698, -1.09153792],
       [-0.15100718, -0.98601141, -0.17233841, ..., -0.17540649,
         0.75260114,  0.64090421],
       [ 2.12401674, -0.49969604,  1.99050816, ...,  1.00470796,
        -0.66168704, -1.03451814],
       ...,
       [-0.16513776,  1.22324984, -0.19329702, ...,  0.24826384,
         0.88645053, -0.28526756],
       [ 1.82162226, -0.47653817,  1.73982672, ...,  1.45456882,
        -0.37302389, -0.73556396],
       [ 1.08400581, -0.59232754,  1.02887773, ...,  0.56563143,
        -0.12628946, -0.11207663]])

In [14]:
encoder = LabelEncoder().fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1])

## Changing the numpy arrays to pytorch

In [23]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [24]:
X_train_tensor.dtype, type(X_train_tensor), X_train_tensor.shape

(torch.float64, torch.Tensor, torch.Size([455, 30]))

In [25]:
X_train_tensor

tensor([[ 0.5301,  0.0561,  0.4782,  ...,  0.5425, -0.4359, -1.0915],
        [-0.1510, -0.9860, -0.1723,  ..., -0.1754,  0.7526,  0.6409],
        [ 2.1240, -0.4997,  1.9905,  ...,  1.0047, -0.6617, -1.0345],
        ...,
        [-0.1651,  1.2232, -0.1933,  ...,  0.2483,  0.8865, -0.2853],
        [ 1.8216, -0.4765,  1.7398,  ...,  1.4546, -0.3730, -0.7356],
        [ 1.0840, -0.5923,  1.0289,  ...,  0.5656, -0.1263, -0.1121]],
       dtype=torch.float64)

In [26]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model for the Nerual Network(start)

In [40]:
class MySimpleNN():
    
    def __init__(self, train_data):
        self.weights = torch.rand(train_data.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    
    def forward(self, train_data):
        z = torch.matmul(train_data, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_true):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss

#### Important Parameters to use

In [60]:
learning_rate = 0.2
epochs = 100

### Training Pipeline

In [61]:
# create the model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
        
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculation
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        
    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    # print loss for each epoch
    print(f'Epoch: {epoch+1} | Loss = {loss.item()}')

Epoch: 1 | Loss = 3.9436929945445267
Epoch: 2 | Loss = 3.707955212880393
Epoch: 3 | Loss = 3.440717779745967
Epoch: 4 | Loss = 3.1554049954983063
Epoch: 5 | Loss = 2.8515783788525053
Epoch: 6 | Loss = 2.5389049422517704
Epoch: 7 | Loss = 2.2239569583770438
Epoch: 8 | Loss = 1.8895139349409387
Epoch: 9 | Loss = 1.5853374755960254
Epoch: 10 | Loss = 1.3325478668594892
Epoch: 11 | Loss = 1.1425536921845105
Epoch: 12 | Loss = 1.010085218149911
Epoch: 13 | Loss = 0.9199196824829633
Epoch: 14 | Loss = 0.858297695587967
Epoch: 15 | Loss = 0.8149930068275087
Epoch: 16 | Loss = 0.7836202915956604
Epoch: 17 | Loss = 0.7604926539231169
Epoch: 18 | Loss = 0.7433017932935866
Epoch: 19 | Loss = 0.7304215423569044
Epoch: 20 | Loss = 0.7206517028975785
Epoch: 21 | Loss = 0.7131179175907838
Epoch: 22 | Loss = 0.7072008859381418
Epoch: 23 | Loss = 0.7024704369072234
Epoch: 24 | Loss = 0.6986289982873609
Epoch: 25 | Loss = 0.6954685938622674
Epoch: 26 | Loss = 0.6928408394175306
Epoch: 27 | Loss = 0.6906370912127416
Epoch: 28 | Loss = 0.6887756623834715
Epoch: 29 | Loss = 0.6871936443449401
Epoch: 30 | Loss = 0.6858416210671456
Epoch: 31 | Loss = 0.6846801729216612
Epoch: 32 | Loss = 0.6836774893316013
Epoch: 33 | Loss = 0.6828076795981354
Epoch: 34 | Loss = 0.6820495358904294
Epoch: 35 | Loss = 0.6813855999177415
Epoch: 36 | Loss = 0.68080144180478
Epoch: 37 | Loss = 0.6802850929698814
Epoch: 38 | Loss = 0.6798265944549504
Epoch: 39 | Loss = 0.6794176340385634
Epoch: 40 | Loss = 0.679051252908759
Epoch: 41 | Loss = 0.6787216075464243
Epoch: 42 | Loss = 0.6784237758152926
Epoch: 43 | Loss = 0.6781535986543823
Epoch: 44 | Loss = 0.6779075505557017
Epoch: 45 | Loss = 0.6776826333791343
Epoch: 46 | Loss = 0.6774762891265113
Epoch: 47 | Loss = 0.6772863281445002
Epoch: 48 | Loss = 0.6771108699029106
Epoch: 49 | Loss = 0.6769482940385185
Epoch: 50 | Loss = 0.6767971997921116
Epoch: 51 | Loss = 0.6766563723194539
Epoch: 52 | Loss = 0.6765247546419303
Epoch: 53 | Loss = 0.6764014242330038
Epoch: 54 | Loss = 0.6762855734229488
Epoch: 55 | Loss = 0.6761764929551143
Epoch: 56 | Loss = 0.6760735581491243
Epoch: 57 | Loss = 0.6759762172254548
Epoch: 58 | Loss = 0.6758839814262071
Epoch: 59 | Loss = 0.6757964166322201
Epoch: 60 | Loss = 0.6757131362298144
Epoch: 61 | Loss = 0.6756337950237827
Epoch: 62 | Loss = 0.6755580840285916
Epoch: 63 | Loss = 0.6754857259986689
Epoch: 64 | Loss = 0.6754164715823271
Epoch: 65 | Loss = 0.6753500960032955
Epoch: 66 | Loss = 0.6752863961898092
Epoch: 67 | Loss = 0.6752251882843529
Epoch: 68 | Loss = 0.6751663054780236
Epoch: 69 | Loss = 0.6751095961224474
Epoch: 70 | Loss = 0.6750549220796374
Epoch: 71 | Loss = 0.6750021572763629
Epoch: 72 | Loss = 0.674951186434742
Epoch: 73 | Loss = 0.674901903955071
Epoch: 74 | Loss = 0.6748542129304945
Epoch: 75 | Loss = 0.6748080242761267
Epoch: 76 | Loss = 0.6747632559577702
Epoch: 77 | Loss = 0.6747198323075014
Epoch: 78 | Loss = 0.6746776834151942
Epoch: 79 | Loss = 0.6746367445865737
Epoch: 80 | Loss = 0.6745969558596775
Epoch: 81 | Loss = 0.6745582615727062
Epoch: 82 | Loss = 0.6745206099771688
Epoch: 83 | Loss = 0.6744839528910402
Epoch: 84 | Loss = 0.674448245387315
Epoch: 85 | Loss = 0.6744134455139417
Epoch: 86 | Loss = 0.6743795140416213
Epoch: 87 | Loss = 0.6743464142363833
Epoch: 88 | Loss = 0.6743141116542384
Epoch: 89 | Loss = 0.6742825739555228
Epoch: 90 | Loss = 0.6742517707368385
Epoch: 91 | Loss = 0.6742216733787337
Epoch: 92 | Loss = 0.6741922549074877
Epoch: 93 | Loss = 0.6741634898695443
Epoch: 94 | Loss = 0.6741353542173086
Epoch: 95 | Loss = 0.674107825205162
Epoch: 96 | Loss = 0.6740808812946718
Epoch: 97 | Loss = 0.6740545020680953
Epoch: 98 | Loss = 0.6740286681493581
Epoch: 99 | Loss = 0.6740033611317933
Epoch: 100 | Loss = 0.6739785635119832

In [62]:
model.weights[:10], model.bias

(tensor([[ 0.0769],
         [ 0.0218],
         [ 0.0967],
         [-0.2719],
         [ 0.2236],
         [-0.0164],
         [ 0.2486],
         [-0.1434],
         [-0.0968],
         [-0.0448]], dtype=torch.float64, grad_fn=<SliceBackward0>),
 tensor([-0.4220], dtype=torch.float64, requires_grad=True))

### Evaluation

In [69]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.7).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.719298243522644