## torch.nn Module

The torch.nn module in PyTorch is a core library that provides a wide array of classes and functions designed to help developers build neural networks efficiently and effectively. It abstracts the complexity of creating and training neural networks by offering pre-built layers, loss functions, activation functions, and other utilities, enabling you to focus on designing and experimenting with model architectures.

Key Components of torch.nn:

1. **Modules (Layers)**:
    * nn.Module: The base class for all neural network modules. Your custom models and layers should subclass this class.
    * Common Layers: Includes layers like nn.Linear (fully connected layer), nn.Conv2d (convolutional layer), nn.LSTM (recurrent layer), and many others.

2. **Activation Functions**:
    * Functions like nn.ReLU, nn.Sigmoid, and nn.Tanh introduce non-linearities to the model, allowing it to learn complex patterns.

3. **Loss Functions**:
    * Provides loss functions such as nn.CrossEntropyLoss, nn.MSELoss, and nn.NLLLoss to quantify the difference between the model's predictions and the actual targets

4. **Container Modules**:
    * nn.Sequential: A sequential container to stack layers in order.

5. **Regularization and Dropout**:
    * Layers like nn.Dropout and nn.BatchNorm2d help prevent overfitting and improve the model's ability to generalize to new data.

In [7]:
import torch
import torch.nn as nn
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

#### Load the dataset

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [9]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [10]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

### Train Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [12]:
X_train.shape, X_test.shape

((455, 30), (114, 30))

### Scaling Numeric Columns

In [13]:
scaler = StandardScaler().fit(X_train.select_dtypes(include='number'))
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.09226692,  0.03079149,  0.0692189 , ..., -0.30971854,
        -0.69226058, -0.5313923 ],
       [ 2.5461265 ,  1.76872043,  2.69163931, ...,  2.40770218,
         0.46689778,  0.16663052],
       [-0.6164391 , -0.84410044, -0.63252701, ..., -0.61032631,
         0.75549154, -0.28367212],
       ...,
       [ 1.4928717 ,  3.14388931,  1.43823187, ...,  0.71008031,
        -0.30640594, -0.47497013],
       [ 1.08669632,  0.62353669,  1.00826039, ..., -0.37299632,
        -0.85489352, -1.01769765],
       [ 0.97464793,  0.3627288 ,  1.00826039, ...,  0.54154384,
        -0.7050161 , -0.38361996]])

### Encoding the Categorical Columns

In [15]:
encoder = LabelEncoder().fit(y_train)
y_train = encoder.transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

## Changing the numpy arrays to pytorch

In [36]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [37]:
X_train_tensor.dtype, type(X_train_tensor), X_train_tensor.shape

(torch.float32, torch.Tensor, torch.Size([455, 30]))

In [38]:
X_train_tensor

tensor([[ 0.0923,  0.0308,  0.0692,  ..., -0.3097, -0.6923, -0.5314],
        [ 2.5461,  1.7687,  2.6916,  ...,  2.4077,  0.4669,  0.1666],
        [-0.6164, -0.8441, -0.6325,  ..., -0.6103,  0.7555, -0.2837],
        ...,
        [ 1.4929,  3.1439,  1.4382,  ...,  0.7101, -0.3064, -0.4750],
        [ 1.0867,  0.6235,  1.0083,  ..., -0.3730, -0.8549, -1.0177],
        [ 0.9746,  0.3627,  1.0083,  ...,  0.5415, -0.7050, -0.3836]])

In [39]:
y_train_tensor.shape

torch.Size([455])

## Create the Perceptron Model

In [48]:
class Model(nn.Module):
    
    # create constructor of our Model clas
    def __init__(self, num_features):
        
        # call the constructor of the nn.Module class
        super().__init__()
        
        # creating a layer -> a linear layer
        self.linear = nn.Linear(num_features, 1) # nn.Linear(number of inputs, number of outputs)
        self.sigmoid = nn.Sigmoid() # sigmoid activation function
        
    def forward(self, features):
        
        # giving the input to the forward pass i.e. the linear layer : wx+b
        out = self.linear(features)
        
        # after the linear layer give the output to the activation function: sigmoid(wx+b)
        out = self.sigmoid(out)
        
        # return the final output after activation
        return out
    
    def loss(self, y_pred, y_true):
        loss_func = nn.BCEWithLogitsLoss()
        loss = loss_func(y_pred, y_true)
        return loss

In [78]:
epochs = 100
learning_rate = 0.1

In [79]:
model = Model(X_train.shape[1])

for epoch in range(epochs):
    
    #forward pass
    y_pred = model(X_train_tensor)
    
    # calculate loss
    loss = model.loss(y_pred.squeeze(), y_train_tensor)
    print(f'Epoch: {epoch} | Loss: {loss.item():.4f}')
    
    # backward pass : calculete gredient for loss
    loss.backward()
    
    # parameter update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad
        
    # zeor gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

Epoch: 0 | Loss: 0.7640
Epoch: 1 | Loss: 0.7540
Epoch: 2 | Loss: 0.7447
Epoch: 3 | Loss: 0.7362
Epoch: 4 | Loss: 0.7283
Epoch: 5 | Loss: 0.7211
Epoch: 6 | Loss: 0.7145
Epoch: 7 | Loss: 0.7084
Epoch: 8 | Loss: 0.7028
Epoch: 9 | Loss: 0.6977
Epoch: 10 | Loss: 0.6929
Epoch: 11 | Loss: 0.6885
Epoch: 12 | Loss: 0.6844
Epoch: 13 | Loss: 0.6805
Epoch: 14 | Loss: 0.6770
Epoch: 15 | Loss: 0.6736
Epoch: 16 | Loss: 0.6705
Epoch: 17 | Loss: 0.6676
Epoch: 18 | Loss: 0.6648
Epoch: 19 | Loss: 0.6622
Epoch: 20 | Loss: 0.6598
Epoch: 21 | Loss: 0.6575
Epoch: 22 | Loss: 0.6553
Epoch: 23 | Loss: 0.6532
Epoch: 24 | Loss: 0.6512
Epoch: 25 | Loss: 0.6494
Epoch: 26 | Loss: 0.6476
Epoch: 27 | Loss: 0.6459
Epoch: 28 | Loss: 0.6443
Epoch: 29 | Loss: 0.6427
Epoch: 30 | Loss: 0.6412
Epoch: 31 | Loss: 0.6398
Epoch: 32 | Loss: 0.6385
Epoch: 33 | Loss: 0.6372
Epoch: 34 | Loss: 0.6359
Epoch: 35 | Loss: 0.6347
Epoch: 36 | Loss: 0.6336
Epoch: 37 | Loss: 0.6324
Epoch: 38 | Loss: 0.6314
Epoch: 39 | Loss: 0.6303
Epoch: 40 | Loss: 0.6293
Epoch: 41 | Loss: 0.6284
Epoch: 42 | Loss: 0.6274
Epoch: 43 | Loss: 0.6265
Epoch: 44 | Loss: 0.6257
Epoch: 45 | Loss: 0.6248
Epoch: 46 | Loss: 0.6240
Epoch: 47 | Loss: 0.6232
Epoch: 48 | Loss: 0.6225
Epoch: 49 | Loss: 0.6217
Epoch: 50 | Loss: 0.6210
Epoch: 51 | Loss: 0.6203
Epoch: 52 | Loss: 0.6196
Epoch: 53 | Loss: 0.6189
Epoch: 54 | Loss: 0.6183
Epoch: 55 | Loss: 0.6177
Epoch: 56 | Loss: 0.6171
Epoch: 57 | Loss: 0.6165
Epoch: 58 | Loss: 0.6159
Epoch: 59 | Loss: 0.6153
Epoch: 60 | Loss: 0.6148
Epoch: 61 | Loss: 0.6142
Epoch: 62 | Loss: 0.6137
Epoch: 63 | Loss: 0.6132
Epoch: 64 | Loss: 0.6127
Epoch: 65 | Loss: 0.6122
Epoch: 66 | Loss: 0.6117
Epoch: 67 | Loss: 0.6113
Epoch: 68 | Loss: 0.6108
Epoch: 69 | Loss: 0.6104
Epoch: 70 | Loss: 0.6099
Epoch: 71 | Loss: 0.6095
Epoch: 72 | Loss: 0.6091
Epoch: 73 | Loss: 0.6087
Epoch: 74 | Loss: 0.6083
Epoch: 75 | Loss: 0.6079
Epoch: 76 | Loss: 0.6075
Epoch: 77 | Loss: 0.6072
Epoch: 78 | Loss: 0.6068
Epoch: 79 | Loss: 0.6064
Epoch: 80 | Loss: 0.6061
Epoch: 81 | Loss: 0.6057
Epoch: 82 | Loss: 0.6054
Epoch: 83 | Loss: 0.6051
Epoch: 84 | Loss: 0.6047
Epoch: 85 | Loss: 0.6044
Epoch: 86 | Loss: 0.6041
Epoch: 87 | Loss: 0.6038
Epoch: 88 | Loss: 0.6035
Epoch: 89 | Loss: 0.6032
Epoch: 90 | Loss: 0.6029
Epoch: 91 | Loss: 0.6026
Epoch: 92 | Loss: 0.6023
Epoch: 93 | Loss: 0.6020
Epoch: 94 | Loss: 0.6018
Epoch: 95 | Loss: 0.6015
Epoch: 96 | Loss: 0.6012
Epoch: 97 | Loss: 0.6010
Epoch: 98 | Loss: 0.6007
Epoch: 99 | Loss: 0.6005

In [80]:
# show the model weights
print(model.linear.weight)

# show the model bias
print(model.linear.bias)

Parameter containing:
tensor([[ 0.2781,  0.1504,  0.2824,  0.4411,  0.1119, -0.0017,  0.1623,  0.2803,
          0.1492, -0.0427,  0.0880,  0.1004,  0.1216,  0.1469,  0.0979,  0.1135,
          0.0173,  0.1386,  0.0709, -0.0786,  0.4734,  0.2766,  0.3831,  0.2789,
          0.2781,  0.3531,  0.1315,  0.2765,  0.2434,  0.0334]],
       requires_grad=True)
Parameter containing:
tensor([-0.1719], requires_grad=True)

### Evaluation

In [94]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9999).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6578947305679321

## visualize the neural network
use torchinfo library to visualize the neural network

In [82]:
from torchinfo import summary

summary(model, input_size=X_train_tensor.shape)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================